/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidemo_JniUtil */

#ifndef _Included_com_example_jnidemo_JniUtil
#define _Included_com_example_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnidemo_JniUtil
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JniUtil_sayHello
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JniUtil_testNativeCrash
    (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JniUtil_testNativeAnr
    (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
