/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnidemo_JniUtil */

#ifndef _Included_com_example_jnidemo_JniUtil
#define _Included_com_example_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnidemo_JniUtil
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JniUtil_sayHello
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JniUtil_testNativeCrash
    (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_example_jnidemo_JniUtil_testNativeAnr
    (JNIEnv *, jclass);

#define JNI_CLASS_NAME "com/example/jnidemo/JniUtil"
#define JNI_METHOD_GET_STRING_FROM_JAVA "getStringFromJava"
#define JNI_METHOD_GET_STRING_FROM_JAVA_SIGNATURE "(Ljava/lang/String;)Ljava/lang/String;"
#define JNI_METHOD_CALL_JAVA_METHOD "callJavaMethod"
#define JNI_METHOD_CALL_JAVA_METHOD_SIGNATURE "(Ljava/lang/String;)V"

#ifdef __cplusplus
}
#endif
#endif
